/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Employee;
import model.EmployeeHistory;

/**
 * This is a test comment 
 * 
 *  */
/**
 *
 * @author anush
 */
public class CreateEmployee extends javax.swing.JPanel {

    /**
     * Creates new form CreateEmployee
     */
    Employee emp;   //to store the employee temporarily
    EmployeeHistory history;

    public CreateEmployee(EmployeeHistory e) {
        initComponents();
        this.history = e;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Age = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Gender = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Level = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Team = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Position = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Contact = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Photo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        EmployeeId = new javax.swing.JTextField();
        BtnSave = new javax.swing.JButton();
        MaleRB = new javax.swing.JRadioButton();
        FemaleRB = new javax.swing.JRadioButton();
        OtherRB = new javax.swing.JRadioButton();
        StartDate = new com.toedter.calendar.JDateChooser();
        UploadPhoto = new javax.swing.JButton();
        Email = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        jLabel1.setText("Employee ID");

        jLabel2.setText("Name");

        jLabel3.setText("Age");

        jLabel4.setText("Gender");

        jLabel5.setText("Start Date");

        jLabel6.setText("Level");

        jLabel7.setText("Team");

        jLabel8.setText("Position");

        jLabel9.setText("Contact");

        jLabel10.setText("Photo");

        BtnSave.setText("Save");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        buttonGroup1.add(MaleRB);
        MaleRB.setText("Male");
        MaleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleRBActionPerformed(evt);
            }
        });

        buttonGroup1.add(FemaleRB);
        FemaleRB.setText("Female");
        FemaleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleRBActionPerformed(evt);
            }
        });

        buttonGroup1.add(OtherRB);
        OtherRB.setText("Other");
        OtherRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherRBActionPerformed(evt);
            }
        });

        UploadPhoto.setText("Browse");
        UploadPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadPhotoActionPerformed(evt);
            }
        });

        jLabel11.setText("Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addComponent(EmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                                        .addGap(56, 56, 56))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Email)
                                    .addComponent(StartDate, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(Age)
                                    .addComponent(Team)
                                    .addComponent(Contact))))
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(MaleRB)
                                        .addGap(18, 18, 18)
                                        .addComponent(FemaleRB)
                                        .addGap(18, 18, 18)
                                        .addComponent(OtherRB))
                                    .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(Gender)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Photo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(UploadPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(Level)
                                    .addComponent(Position)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addComponent(BtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(EmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Team, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OtherRB)
                            .addComponent(FemaleRB)
                            .addComponent(MaleRB))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(Photo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UploadPhoto))
                .addGap(48, 48, 48)
                .addComponent(BtnSave)
                .addContainerGap(128, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        // TODO add your handling code here:

        int id = 0, age=0, level=0;
        String name="", gender="", startdate="", team="", position="", photo="", email="";
        long contact=0;
        if (isValidId(EmployeeId.getText())) {
            id = Integer.parseInt(EmployeeId.getText());
        } else {
            JOptionPane.showMessageDialog(this, "Enter valid id");
        }
        if (isValidUsername(Name.getText())) {
            name = Name.getText();
        } else {
            JOptionPane.showMessageDialog(this, "Enter valid name");
        }
        if (onlyDigits(Age.getText(), Age.getText().length())) {
            if (isValidAge(Age.getText())) {
                age = Integer.parseInt(Age.getText());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Enter valid age");
        }
        gender = Gender.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        startdate = sdf.format(StartDate.getDate());
        if(isValidLevel(Level.getText())){   
            level = Integer.parseInt(Level.getText());
        }
        else{
            JOptionPane.showMessageDialog(this, "Enter valid level");
        }
        team = Team.getText();
        position = Position.getText();
        if(isValidContact(Contact.getText())){
            contact = Long.parseLong(Contact.getText());
        }
        else{
            JOptionPane.showMessageDialog(this, "Enter valid contact");
        }
        if(isEmailValid(Email.getText())){
            email = Email.getText();
        }
        else{
            JOptionPane.showMessageDialog(this, "Enter valid email");
        }
        photo = Photo.getText();
        Employee e = history.addNewEmployee();
        e.setId(id);
        e.setName(name);
        e.setAge(age);
        e.setGender(gender);
        e.setDate(startdate);
        e.setLevel(level);
        e.setTeam(team);
        e.setPosition(position);
        e.setContact(contact);
        e.setEmail(email);
        e.setPhoto(photo);
        JOptionPane.showMessageDialog(this, "Record Saved!");
        EmployeeId.setText("");
        Name.setText("");
        Age.setText("");
        Gender.setText("");
        StartDate.setDate(null);
        Level.setText("");
        Team.setText("");
        Position.setText("");
        Contact.setText("");
        Email.setText("");
        Photo.setText("");
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void MaleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleRBActionPerformed
        // TODO add your handling code here:
        if(MaleRB.isSelected()){
            Gender.setText("Male");
        }
    }//GEN-LAST:event_MaleRBActionPerformed

    private void FemaleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleRBActionPerformed
        // TODO add your handling code here:
        if(FemaleRB.isSelected()){
            Gender.setText("Female");
        }
    }//GEN-LAST:event_FemaleRBActionPerformed

    private void OtherRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtherRBActionPerformed
        // TODO add your handling code here:
        if(OtherRB.isSelected()){
            Gender.setText("Other");
        }
    }//GEN-LAST:event_OtherRBActionPerformed

    private void UploadPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadPhotoActionPerformed
        // TODO add your handling code here:
        JFileChooser browseimage = new JFileChooser();
        int showOpenDialog = browseimage.showOpenDialog(null);
        if(showOpenDialog == JFileChooser.APPROVE_OPTION){
            File imageFile = browseimage.getSelectedFile();
            String img = imageFile.getAbsolutePath();
            Photo.setText(img);
        }
    }//GEN-LAST:event_UploadPhotoActionPerformed

    //Validation functions
    public static boolean isValidUsername(String name) {
        String regex = "^[A-Za-z]\\w{5,29}$";
        Pattern p = Pattern.compile(regex);
        if (name == null) {
            return false;
        }
        Matcher m = p.matcher(name);
        return m.matches();
    }

    public boolean isValidId(String text) {
        int len = text.length();
        if (onlyDigits(text, len)) {
            String regex = "[0-9]{5}";
            Pattern p = Pattern.compile(regex);
            if (text == null) {
                return false;
            }
            Matcher m = p.matcher(text);
            return m.matches();
        }
        return true;
    }

    public static boolean onlyDigits(String str, int n) {
        for (int i = 0; i < n; i++) {
            if (!Character.isDigit(str.charAt(i))) {
                return false;
            }
        }
        return true;
    }

    public boolean isValidAge(String str) {
        String regex = "(100)|(0*\\d{1,2})";
        Pattern p = Pattern.compile(regex);
        if (Age.getText() == null) {
            return false;
        }
        Matcher m = p.matcher(str);
        return m.matches();
    }
    
    public boolean isValidContact(String str){
        String regex = "\\d{3}-\\d{3}-\\d{4}";
        Pattern p = Pattern.compile(regex);
        if (Contact.getText() == null) {
            return false;
        }
        Matcher m = p.matcher(str);
        return m.matches();
    }
    
    public boolean isValidLevel(String text) {
        String regex = "[1-9]|10";
        Pattern p = Pattern.compile(regex);
        if (Level.getText() == null) {
            return false;
        }
        Matcher m = p.matcher(text);
        return m.matches();
    }    
    
    public boolean isEmailValid(String str){
        String regex = "^(.+)@(.+)$";
        Pattern p = Pattern.compile(regex);
        if (Email.getText() == null) {
            return false;
        }
        Matcher m = p.matcher(str);
        return m.matches();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age;
    private javax.swing.JButton BtnSave;
    private javax.swing.JTextField Contact;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField EmployeeId;
    private javax.swing.JRadioButton FemaleRB;
    private javax.swing.JTextField Gender;
    private javax.swing.JTextField Level;
    private javax.swing.JRadioButton MaleRB;
    private javax.swing.JTextField Name;
    private javax.swing.JRadioButton OtherRB;
    private javax.swing.JTextField Photo;
    private javax.swing.JTextField Position;
    private com.toedter.calendar.JDateChooser StartDate;
    private javax.swing.JTextField Team;
    private javax.swing.JButton UploadPhoto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables


}
